import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Example from "../components/example";
import Exampletwo from "../components/exampletwo";
import Examplethree from "../components/examplethree";
import Eventheader from "../components/eventheader"


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ticketchain</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />

        <link rel="icon" href="/favicon2.png" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" />
      

      </Head>

      <header className={styles.header}>
        <div className={styles.leftSection}>
          <span className={styles.logo}>ticketchain</span>
        </div>
        <div className={styles.rightSection}>
          <ConnectButton  />
        </div>
      </header>
      

   
      
      

      <main className={styles.main}>
        <div><Eventheader/></div>
      

        


        <div className={styles.grid}>
          <div style={{ marginBottom: '2rem' }}><Example /></div>
          <div style={{ marginBottom: '2rem' }}><Exampletwo /></div>
          <div style={{ marginBottom: '2rem' }}><Examplethree /></div>
         

         

     

      
        </div>
      </main>

      <footer className={styles.footer}>
        <div><p>Made with ❤️ by ticketchain, © 2023, ltd. All rights reserved.</p>
        <p>     <a href="https://www.linkedin.com/in/mustafa-o-0b7a8aab/" target="_blank" rel="noopener noreferrer">
        <img src="/linkedintransparent2.png" alt="LinkedIn Icon" width="40" height="40" style={{ width: '40px', height: '40px !important' }} />

            
          </a></p></div>

     
      </footer>
    </div>
  );
};

export default Home;
