import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ticketchain</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />

        <link rel="icon" href="/favicon2.png" />
      

      </Head>

      <header className={styles.header}>
        <div className={styles.leftSection}>
          <span className={styles.logo}>ticketchain</span>
        </div>
        <div className={styles.rightSection}>
          <ConnectButton  />
        </div>
      </header>

      <main className={styles.main}>

        

        

        <div className={styles.grid}>
          
         

         

     

      
        </div>
      </main>

      <footer className={styles.footer}>
        <div><p>Made with ❤️ by ticketchain, © 2023, ltd. All rights reserved.</p>
        <p>     <a href="https://www.linkedin.com/in/mustafa-o-0b7a8aab/" target="_blank" rel="noopener noreferrer">
        <img src="/linkedintransparent2.png" alt="LinkedIn Icon" width="40" height="40" style={{ width: '40px', height: '40px !important' }} />

            
          </a></p></div>

     
      </footer>
    </div>
  );
};

export default Home;
